export const khmerLabels: Record<string, string> = {
  person: "មនុស្ស",
  chair: "កៅអី",
  cup: "ពែង",
  bottle: "ដប",
  laptop: "កុំព្យូទ័រ",
  "cell phone": "ទូរស័ព្ទ",
  book: "សៀវភៅ",
  tv: "ទូរទស្សន៍",
  mouse: "កណ្តុរ",
  car: "រថយន្ត",
  bicycle: "កង់",
  motorcycle: "មូតូ",
  bus: "បូស",
  truck: "រថយន្តដឹក",
  cat: "ឆ្មា",
  dog: "ឆ្កែ",
  bird: "សត្វបក្សី",
  cow: "គោ",
  elephant: "ដំរី",
  horse: "សេះ",
  sheep: "សត្វចៀម",
  bear: "ខ្លា",
  banana: "ចេក",
  apple: "ប៉ោម",
  orange: "ក្រូច",
  pizza: "ភីហ្សា",
  cake: "នំ",
  sandwich: "សាំងវិច",
  carrot: "당근",
  broccoli: "ប្រូខូលី",
  "hot dog": "សាច់ក្រក",
  fork: "សម",
  knife: "កាំបិត",
  spoon: "ស្លាបព្រា",
  bowl: "ចាន",
  bed: "គ្រែ",
  couch: "សាឡុង",
  toilet: "បង្គន់",
  sink: "អាងលាងដៃ",
  refrigerator: "ទូទឹកកក",
  microwave: "ម៉ាស៊ីនកំដៅ",
  oven: "ឡដុត",
  toaster: "ម៉ាស៊ីនដុតនំប៉័ង",
  clock: "នាឡិកា",
  vase: "ល្អី",
  scissors: "កាត់",
  backpack: "កាបូបស្ពាយ",
  handbag: "កាបូប",
  umbrella: "ឆ័ត្រ",
  tie: "ដងខ្សាច់",
  suitcase: "វ៉ាលីស",
  bench: "កៅអីវែង",
  table: "តុ",
  "dining table": "តុបាយ",
  "potted plant": "ដើមឈើ",
  "stop sign": "សញ្ញាឈប់",
  "traffic light": "អំពូលស្តុប",
  "fire hydrant": "បំពង់ពន្លត់អគ្គិភ័យ",
  "parking meter": "គ្រឿងចាត់ចែងចំណត",
  "sports ball": "បាល់",
  kite: "គ្រាប់បាល់",
  skateboard: "ស្គីបត",
  surfboard: "ក្តារស្គីទឹក",
  skis: "ស្គីទឹកកក",
  snowboard: "ស្នូប៊ត",
  "tennis racket": "របាល់ tennis",
  "baseball bat": "បន្ទះបេស្បល",
  "baseball glove": "ស្រោមដៃបេស្បល",
  frisbee: "ចានហោះ",
  "wine glass": "កែវស្រា",
  airplane: "យន្តហោះ",
  train: "រថភ្លើង",
  boat: "នាវា",
  zebra: "សេះក្រឡុក",
  giraffe: "កាមេ",
  "teddy bear": "តុក្កតាខ្លា",
  "hair drier": "ម៉ាស៊ីនផ្លុំសក់",
  toothbrush: "ច្រាសដុសធ្មេញ",
  remote: "រីម៉ូត",
}